config/routes.rb
Myblog::Application.routes.draw do

resources :users

 

  resources :entries do
  	   resources :comments
  end

  resources :categories do 

resources :entries
end

  
  resources :blog
  
  resources :blogs
  resources :sessions

match "/show" =>"blogs#show"
match "/readmore" =>"blogs#readmore"
match "/all" =>"blogs#all"

get 'logout', to: 'sessions#destroy', as: 'logout'
get 'login', to:  'sessions#new', as: 'login'

root :to=>"home#index"
   
 

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :category 
	has_many :comments
	
	
def self.most_recent
first(:order => 'id DESC') # or whatever query you need to get the most recent
end
	
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @category = Category.find(params[:category_id])
    @entries = @category.entries.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @category = Category.find(params[:category_id])
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    
    @entry = Entry.new(params[:entry])
    if  @entry.save
    @category = Category.find_by_id(@entry.category_id)
        redirect_to category_entries_path(@category), notice: 'Entry was successfully created.' 
    else
        format.html { render action: "new" }
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<p>
<b>entry</b>
<%= entry.subject%>
<%= link_to 'readmore', entry_path(entry) %>
</p>

<p>
<b>body</b>
<%= truncate entry.body, :length => 20 %>
</p>
<%=render "comments/form" %>

app/views/entries/_form.html.erb
<%= form_for @entry, :html => { :class => "form-horizontal"} do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="control-group">
<label class="control-label" for="inputEmail">   Subject:</label>
<div class="controls">
 <%= f.text_field :subject %>
</div>
</div>


<div class="control-group">
<label class="control-label" for="inputEmail">   Body:</label>
<div class="controls">
 <%= f.text_area :body,:rows=>"3" %>
</div>
</div>

<div class="control-group">
<label class="control-label" for="inputEmail">   </label>
<div class="controls">
 <%= f.hidden_field :category_id, :value=>params[:category_id] %>
</div>
</div>
    
<div class="controls">
<%= f.submit "Add Entry", {:class => "btn btn-primary btn-indent pull-center"} %>
</div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div class="page-header">
  <h2>Entries</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <h3 class="muted">Total-Entries&nbsp;
<span class="badge badge-warning"><%= @entries.size %></span></h3>
  <%= link_to 'New Entry',new_category_entry_path, :class => "btn btn-primary pull-right button-up"  %>
</div>




<% @entries.each do |post| %>
    <div class="well well-large">
    <h4><%= link_to post.subject,category_entry_path(@category,post) %></h4>

   <h5>Total-Comments &nbsp;
   <span class="badge badge-warning"><%= post.comments.size %></span>
  </h5>

  <%= post.body %>
  </br>
	Posted <%= time_ago_in_words post.created_at %>...ago 
  </div>
<% end %>
 

		



  

app/views/entries/new.html.erb
<div class="page-header">
	<h1>New Entry</h1>
    <%= link_to 'Back', categories_path ,  :class => "btn btn-primary pull-right button-up" %>
</div>
<b style="color:green"><%= notice %></b>
<%= render 'form' %>

app/views/entries/show.html.erb
<div class="page-header">
  <h1><%= @entry.subject %></h1>
</div>
<div class="hero-unit">
<%= @entry.body %>
</div>

<h3 class="muted">Total Comments &nbsp; <span class="badge badge-warning"><%= @entry.comments.size %></span></h3>
<hr>

<% @entry.comments.each do|comment| %>
<p>commented by: <b> <span class="label label-success"><%= comment_user(comment.user_id) %></span></b></p>
<p><%= comment.comment %></p>
<p><%= time_ago_in_words comment.created_at %> ago...</p>
<% if current_user.orgnization_profile.is_admin? %>
<p><%= link_to "delete comment", [@entry,comment], :method => :delete, :confirm => "are you sure?" %></p> 
<% end %>
<hr>
<% end %>

<!-- Form for comments-->

<%= form_for [@entry, @entry.comments.build] do |com| %>
<b>ADD COMMENT:</b><p><%= com.text_area :comment, :size => '30*10' %></p>
<p><%= com.submit "post comment", {:class => "btn btn-primary btn-indent pull-center"} %></p>
<% end %>
<p>