config/routes.rb
Myblog::Application.routes.draw do

resources :users

 

  resources :entries do
  	   resources :comments
  end

  resources :categories do 

resources :entries
end

  
  resources :blog
  
  resources :blogs
  resources :sessions

match "/show" =>"blogs#show"
match "/readmore" =>"blogs#readmore"
match "/all" =>"blogs#all"

get 'logout', to: 'sessions#destroy', as: 'logout'
get 'login', to:  'sessions#new', as: 'login'

root :to=>"home#index"
   
 

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :entries
	scope :recent, limit(5).order('categories.created_at DESC')
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<% if @category.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

<ul>
<% @category.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>


<div class="control-group">
<label class="control-label" for="inputEmail">Category Name </label>
<div class="controls">
<%= f.text_field :name %>
</div>
<div class="controls">
<%= f.submit "Add Category",  {:class => "btn btn-primary btn-indent pull-center"} %>
</div>


<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="page-header">
	<h1>Categories</h1>
    <b style="color:green"><%= notice %></b>
    <%= link_to 'Add Category', new_category_path,  :class => "btn btn-primary pull-right button-up" %>
</div>

</br></br>
<h3 class="muted">Total Categories &nbsp; <span class="badge badge-warning"><%= @categories.size %></span></h3>




<table class="table table-striped">
<% @categories.each_with_index do |category,i| %>
<tr>
<td>&nbsp;</td>
<td><%= i+1 %> </td>
<td>
<b><%= link_to category.name ,category_entries_path(category) %></b>
</td>
<td><b><%= link_to 'Add Entry', new_category_entry_path(category) %><b></td>
<td>
Total-Entries&nbsp;
<span class="badge badge-warning"><%= category.entries.size %></span>
</td>
</tr>

<% end %>
</table>

app/views/categories/new.html.erb
<div class="page-header">
	<h1>New Category</h1>
    <b style="color:green"><%= notice %></b>
    <%= link_to 'Categories', categories_path,  :class => "btn btn-primary pull-right button-up" %>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="page-header">
	<h1>Category</h1>
    
    <%= link_to 'Categories', categories_path,  :class => "btn btn-primary pull-right button-up" %>
</div>

<b style="color:green"><%= notice %></b>
<%= @category.name %>

<%= link_to 'Add Entry', new_category_entry_path(@category) %>||

<%= link_to 'Edit', edit_category_path(@category) %> |