config/routes.rb
Myblog::Application.routes.draw do

resources :users

 

  resources :entries do
  	   resources :comments
  end

  resources :categories do 

resources :entries
end

  
  resources :blog
  
  resources :blogs
  resources :sessions

match "/show" =>"blogs#show"
match "/readmore" =>"blogs#readmore"
match "/all" =>"blogs#all"

get 'logout', to: 'sessions#destroy', as: 'logout'
get 'login', to:  'sessions#new', as: 'login'

root :to=>"home#index"
   
 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
   
    <ul class="nav">
      <li class="active"><%= link_to 'Home', categories_path %></li>
       <li><%= link_to 'Categories', categories_path %></li>
       <li><%= link_to 'Dashboard' %></li>
       <li><%= link_to 'logout', logout_path %></li>
    </ul>
  </div>
</div>
<%= yield %>
</body>
</html>

app/views/layouts/log_in.html.erb


       

<script type="text/javascript">

function signup(link)
{
  window.location.href =link;
}


function select()
{

var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

var email = document.getElementById("email").value; 


 
if(email=="")
 { 
   alert("Please Enter Email");
   document.getElementById("email").focus();
   return false;
 }
 
 else if (reg.test(email) == false)
 {
 
 alert("Please Enter Valid Email");

 return false;  
 }
 
else if (document.getElementById("password").value=="")
{
    alert("Please Enter Password")
    document.getElementById("password").focus();
    
    return false;
}


}
</script>

<div class="page-header">
  <h1>Log In</h1>
  <div class="pull-right"><%= image_tag "rails.png", {:class => "img-rounded"} %></div>
</div>
                                            
  
<b style="color:green"><%= notice %></b>

<%= form_tag sessions_path,{:onsubmit=>"return select();"} do %>
<div align="center">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
    
      <%= text_field_tag :email, params[:email] %>
    </div>
  </div>
  <div class="control-group">
<label class="control-label" for="inputPassword">Password</label>
<div class="controls">
<%= password_field_tag :password %>
</div>
</div>
<div class="control-group">
<div class="controls">
 <%= submit_tag "Sgin in", :class=>"btn"  %> 
<% if notice !="Signed up!" %>&nbsp;&nbsp;
<%= link_to "SignUp", new_user_path %>
</div>
</div>
</div>
<% end %>
<% end %>


